######################################################################
# Automatically generated by qmake (3.0) Sat Jul 4 14:08:40 2015
######################################################################

TEMPLATE = app
TARGET = libmatrix
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11

# Input
SOURCES += Client.cpp Client_requests.cpp Client_slots.cpp libmatrix.cpp
HEADERS += Client.hpp

QT += widgets network
